modLoader="javafml"
loaderVersion="[31,)"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="dynamicregistries"
version="DEV"
displayName="Dynamic Registries Lib"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="examplemod.png"
#credits="null"
authors="rdvdev2"
description='''
A modding library that allows a higher control of the game registries.
'''

[[dependencies.dynamicregistries]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamicregistries]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
